# In modern Docker Compose (Compose V2) you donâ€™t need to specify version at all.
# Docker Compose v2 auto-detects the schema and the version field is now deprecated.

version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ahmed
#      MONGO_INITDB_ROOT_PASSWORD: secret
#      - MONGO_INITDB_ROOT_USERNAME=ahmed # another way to set env vars
    env_file:
      - ./env/mongo.env

  backend:
    build: './backend' # a simple way to build the folder contains Dockerfile
#    build:
#      context: ./backend
#      dockerfile: Dockerfile # you change the file name here to your file name, for example, Dockerfile-dev
#      args:
#        some-arg: value
    ports:
      - '80:80' #host port:container port

    volumes:
      - logs:/app/logs
      - ./backend:/app # we can use a relative path here
      - /app/node_modules # anonymous volume
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb # first run mongodb service as backend depend on mongodb
  frontend:
    build: './frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true # needed1: -it interact with tty
    tty: true # needed2: -it interact with tty
    depends_on:
      - backend
volumes: # just named volumes
  data:
  logs: