services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro

#  php:
#  mysql:
#  composer:
#  artisan:
#  npm: